import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { connect } from 'react-redux'
import { Checkbox, Label } from '@bits-x/checkbox'
import * as Acordion from '@bits-x/accordion'
import { Header } from '@bits-x/header'
import * as Avatar from '@bits-x/avatar'

import styles from '../styles/Home.module.css'
import * as selectors from '../selectors'

type Props = ReturnType<typeof mapStateToProps>

const Home = (props: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        {props.student && (
          <Avatar.Root>
            <Avatar.Image
              alt={props.student.schoolName}
              src={props.student.schoolLogo}
            />
            <Avatar.Name>{props.student.schoolName}</Avatar.Name>
          </Avatar.Root>
        )}
      </Header>
      <main className={styles.main}>
        <Checkbox id="input-title">
          <Label>Check this</Label>
        </Checkbox>
        <Acordion.Root>
          <Acordion.Item>
            <Acordion.Trigger>
              <Acordion.Title>Nombre de categoría</Acordion.Title>
              <Acordion.PrimaryText>title</Acordion.PrimaryText>
              <Acordion.SecondaryText>Content title1</Acordion.SecondaryText>
            </Acordion.Trigger>
            <Acordion.Content>
              Contenido
            </Acordion.Content>
          </Acordion.Item>
          <Acordion.Item>
            <Acordion.Trigger>
              <Acordion.Title>Subrama de materia</Acordion.Title>
              <Acordion.PrimaryText>Dar click aqui</Acordion.PrimaryText>
            </Acordion.Trigger>
            <Acordion.Content>
              Contenido 🙏
            </Acordion.Content>
          </Acordion.Item>
        </Acordion.Root>
      </main>
    </div>
  )
}

const mapStateToProps = (state: any) => ({
  student: selectors.fetchStudent(state).data
})

export default connect(mapStateToProps)(Home)
